// generated by dispel v1; DO NOT EDIT

package admin

type CreateMountIn struct {
	FsParams FsParams `json:"fs_params"`
	FsType   string   `json:"fs_type"`
	Source   string   `json:"source"`
	Target   string   `json:"target"`
}

type CreateRandomServerIn struct {
	BindAddress string `json:"bind_address"`
}

type CreateServerIn struct {
	BindAddress string `json:"bind_address"`
}

type Mount struct {
	Id     string `json:"id"`
	Source string `json:"source"`
	Target string `json:"target"`
}

type Server struct {
	BindAddress string  `json:"bind_address"`
	Mounts      []Mount `json:"mounts"`
	Port        int     `json:"port"`
}
